
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.api.name }}
spec:
  selector:
    app: {{ .Values.api.name }}
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.api.listenPort }}
    targetPort: 
  type: NodePort